import { FileQuestion, LockKeyhole, ShieldAlert, SlidersHorizontal } from "lucide-react";
import Link from "next/link";

export function HelpContent({ supportEmail, supportUrl, abuseReportEmail, abuseReportUrl }: { supportEmail: string | null; supportUrl: string | null; abuseReportEmail: string | null; abuseReportUrl: string | null }) {
  return <><section><h2>Common questions</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[
    { icon: FileQuestion, title: "Why was my file rejected?", copy: "Use a decodable FLAC, MP3, OGG, WAV or WebM file between 3 and 10 seconds and under 10 MB." },
    { icon: SlidersHorizontal, title: "How do I improve a clone?", copy: "Use one speaker, a quiet room, natural pacing and little or no processing." },
    { icon: LockKeyhole, title: "Who can access my audio?", copy: "Audio endpoints check your session and object ownership before serving a result." },
    { icon: ShieldAlert, title: "How do I report misuse?", copy: abuseReportUrl || abuseReportEmail ? "Use the configured operator channel below. Do not include passwords, provider keys, or private audio in the first message." : "This deployment has not configured a monitored reporting channel yet." },
  ].map(({ icon: Icon, title, copy }) => <div className="panel p-5" key={title}><Icon className="h-5 w-5 text-[#a574f2]" /><h3 className="mt-3 font-semibold text-[var(--foreground)]">{title}</h3><p className="mt-2 text-sm leading-6">{copy}</p></div>)}</div></section><section><h2>Safety resources</h2><p>Review the <Link href="/acceptable-use" className="text-[#af82f2]">Acceptable Use Policy</Link> before uploading a sample. If you do not have unambiguous permission, do not upload it.</p>{abuseReportUrl ? <a className="button-secondary mt-4 px-4" href={abuseReportUrl} rel="noreferrer">Report suspected misuse</a> : abuseReportEmail ? <a className="button-secondary mt-4 px-4" href={`mailto:${abuseReportEmail}`}>Report suspected misuse</a> : <p className="mt-3 text-xs text-[var(--warning)]">A monitored abuse-reporting channel is not configured for this deployment.</p>}</section><section><h2>Workspace support</h2>{supportUrl ? <a className="button-secondary mt-4 px-4" href={supportUrl} rel="noreferrer">Open support</a> : supportEmail ? <a className="button-secondary mt-4 px-4" href={`mailto:${supportEmail}`}>Contact {supportEmail}</a> : <p className="mt-3 text-xs text-[var(--warning)]">Operator support is not configured. This deployment is not ready for public support intake.</p>}</section></>;
}
