"use client";

import { Download, Edit3, History, Play, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { AudioPlayer } from "@/components/audio/audio-player";
import { RenameGenerationDialog } from "@/components/generations/rename-generation-dialog";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { useToast } from "@/components/ui/toast";
import { fetchJson } from "@/lib/api/client";
import { formatDuration } from "@/lib/audio/utils";
import type { GenerationDto, VoiceDto } from "@/lib/types/dto";

export function HistoryClient({ initialGenerations, voices }: { initialGenerations: GenerationDto[]; voices: VoiceDto[] }) {
  const [generations, setGenerations] = useState(initialGenerations); const [search, setSearch] = useState(""); const [voice, setVoice] = useState("all"); const [status, setStatus] = useState("all"); const [sort, setSort] = useState("newest"); const [selected, setSelected] = useState<GenerationDto | null>(null); const [remove, setRemove] = useState<GenerationDto | null>(null); const [rename, setRename] = useState<GenerationDto | null>(null); const { showToast } = useToast();
  const filtered = useMemo(() => generations.filter((item) => (item.text.toLowerCase().includes(search.toLowerCase()) || (item.title ?? "").toLowerCase().includes(search.toLowerCase())) && (voice === "all" || item.voiceId === voice) && (status === "all" || item.status === status)).sort((a, b) => sort === "oldest" ? +new Date(a.createdAt) - +new Date(b.createdAt) : +new Date(b.createdAt) - +new Date(a.createdAt)), [generations, search, voice, status, sort]);
  async function deleteItem() { if (!remove) return; try { await fetchJson<void>(`/api/generations/${remove.id}`, { method: "DELETE" }); setGenerations((current) => current.filter((item) => item.id !== remove.id)); if (selected?.id === remove.id) setSelected(null); setRemove(null); showToast("Generation deleted"); } catch (error) { showToast(error instanceof Error ? error.message : "Delete failed.", "error"); } }
  async function renameItem(title: string) { if (!rename) return; try { const result = await fetchJson<{ generation: GenerationDto }>(`/api/generations/${rename.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ title }) }); setGenerations((current) => current.map((item) => item.id === result.generation.id ? result.generation : item)); if (selected?.id === result.generation.id) setSelected(result.generation); setRename(null); showToast("Generation renamed"); } catch (error) { showToast(error instanceof Error ? error.message : "Rename failed.", "error"); } }
  return <><div className="grid gap-3 lg:grid-cols-[1fr_auto_auto_auto]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--muted)]" /><span className="sr-only">Search scripts</span><input className="field pl-10 pr-3" placeholder="Search scripts and titles" value={search} onChange={(event) => setSearch(event.target.value)} /></label><select className="field min-w-[150px] px-3" aria-label="Filter by voice" value={voice} onChange={(event) => setVoice(event.target.value)}><option value="all">All voices</option>{voices.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field min-w-[140px] px-3" aria-label="Filter by status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="READY">Ready</option><option value="FAILED">Failed</option><option value="PROCESSING">Processing</option></select><select className="field min-w-[130px] px-3" aria-label="Sort history" value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option></select></div>
    {selected && <div className="panel mt-5 p-4"><AudioPlayer key={selected.id} generation={selected} onDelete={setRemove} onRename={setRename} /></div>}
    {filtered.length ? <div className="panel mt-5 overflow-hidden"><div className="hidden grid-cols-[minmax(220px,1.5fr)_minmax(140px,.8fr)_100px_120px_auto] gap-4 border-b border-[var(--border-subtle)] px-5 py-3 text-[11px] font-semibold uppercase tracking-[.08em] text-[var(--muted)] md:grid"><span>Generation</span><span>Voice</span><span>Length</span><span>Date</span><span className="text-right">Actions</span></div>{filtered.map((item) => <article key={item.id} className="grid gap-3 border-b border-[var(--border-subtle)] px-5 py-4 last:border-0 md:grid-cols-[minmax(220px,1.5fr)_minmax(140px,.8fr)_100px_120px_auto] md:items-center"><div className="min-w-0"><h2 className="truncate text-sm font-semibold">{item.title || "Untitled voiceover"}</h2><p className="mt-1 truncate text-xs text-[var(--muted)]">{item.text}</p>{item.status === "FAILED" && <p className="mt-1 text-xs text-[var(--danger)]">{item.errorMessageSafe}</p>}</div><p className="text-xs text-[var(--foreground-secondary)]">{item.voiceName}</p><p className="text-xs text-[var(--muted)]">{item.durationMs ? formatDuration(item.durationMs) : `${item.characterCount} chars`}</p><p className="text-xs text-[var(--muted)]">{new Date(item.createdAt).toLocaleDateString()}</p><div className="flex justify-end gap-1"><button type="button" className="icon-button h-9 min-h-9 w-9 min-w-9" onClick={() => setSelected(item)} disabled={!item.audioUrl} aria-label={`Play ${item.title}`}><Play className="h-4 w-4" /></button>{item.audioUrl && <a className="icon-button h-9 min-h-9 w-9 min-w-9" href={`${item.audioUrl}?download=1`} download aria-label={`Download ${item.title}`}><Download className="h-4 w-4" /></a>}<button type="button" className="icon-button h-9 min-h-9 w-9 min-w-9" onClick={() => setRename(item)} aria-label={`Rename ${item.title}`}><Edit3 className="h-4 w-4" /></button><button type="button" className="icon-button h-9 min-h-9 w-9 min-w-9 text-[var(--danger)]" onClick={() => setRemove(item)} aria-label={`Delete ${item.title}`}><Trash2 className="h-4 w-4" /></button></div></article>)}</div> : <div className="panel mt-5 p-12 text-center"><History className="mx-auto h-10 w-10 text-[var(--muted)]" /><h2 className="mt-4 font-semibold">No generations found</h2><p className="mt-2 text-sm text-[var(--muted)]">Your generated voiceovers will appear here.</p></div>}
    <RenameGenerationDialog key={rename?.id ?? "closed"} generation={rename} onOpenChange={(open) => { if (!open) setRename(null); }} onRename={renameItem} /><ConfirmDialog open={Boolean(remove)} onOpenChange={(open) => { if (!open) setRemove(null); }} title="Delete this generation?" description="The stored audio and its history record will no longer be available." confirmLabel="Delete generation" danger onConfirm={deleteItem} /></>;
}
