import { ArrowLeft, CircleUserRound, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { demoSignIn, googleSignIn } from "@/app/actions/auth-actions";
import { VoxMintLogo } from "@/components/branding/voxmint-logo";
import { getCurrentUser } from "@/lib/auth/session";
import { getEnv, isDemoAuthEnabled } from "@/lib/config/env";

export default async function LoginPage({ searchParams }: PageProps<"/login">) {
  if (await getCurrentUser()) redirect("/dashboard");
  const params = await searchParams; const callbackUrl = typeof params.callbackUrl === "string" ? params.callbackUrl : "/dashboard"; const env = getEnv(); const googleReady = Boolean(env.AUTH_GOOGLE_ID && env.AUTH_GOOGLE_SECRET); const demoReady = isDemoAuthEnabled();
  return <main className="grid min-h-screen lg:grid-cols-[.92fr_1.08fr]"><section className="flex flex-col p-6 sm:p-10"><Link href="/"><VoxMintLogo /></Link><div className="mx-auto my-auto w-full max-w-[430px] py-14"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#aa7afa]">Welcome back</p><h1 className="mt-3 text-3xl font-bold tracking-[-0.04em]">Sign in to VoxMint</h1><p className="mt-3 text-sm leading-6 text-[var(--foreground-secondary)]">Access your private voice library and generation history.</p><div className="mt-8 space-y-3">{googleReady && <form action={googleSignIn}><input type="hidden" name="callbackUrl" value={callbackUrl} /><button className="button-secondary w-full"><CircleUserRound className="h-5 w-5" />Continue with Google</button></form>}{demoReady && <form action={demoSignIn}><input type="hidden" name="callbackUrl" value={callbackUrl} /><button className="button-primary w-full"><Sparkles className="h-5 w-5" />Enter demo workspace</button><p className="mt-2 text-center text-[11px] text-[var(--muted)]">Development only · uses the local mock provider</p></form>}{!googleReady && !demoReady && <div className="rounded-[10px] border border-[var(--warning)]/30 bg-[var(--warning)]/5 p-4 text-sm leading-6 text-[var(--foreground-secondary)]">No login provider is configured. Add Google OAuth credentials, or enable development demo auth outside production.</div>}</div><p className="mt-7 text-center text-xs leading-5 text-[var(--muted)]">By continuing, you agree to the <Link href="/terms" className="text-[#af82f2]">Terms</Link> and confirm you will follow the <Link href="/acceptable-use" className="text-[#af82f2]">Acceptable Use Policy</Link>.</p><Link href="/" className="button-ghost mt-7 w-full"><ArrowLeft className="h-4 w-4" />Back to VoxMint</Link></div></section><aside className="relative hidden overflow-hidden border-l border-[var(--border-subtle)] bg-[var(--background-elevated)] lg:flex lg:items-center lg:justify-center lg:p-14"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_35%,rgba(116,71,232,.19),transparent_34%)]" /><div className="panel relative max-w-[560px] p-8"><ShieldCheck className="h-9 w-9 text-[var(--success)]" /><h2 className="mt-6 text-3xl font-bold tracking-[-0.04em]">Your voices stay yours.</h2><p className="mt-4 text-sm leading-7 text-[var(--foreground-secondary)]">Provider keys never enter browser code. Every saved voice, generation, audio route and mutation is checked against the authenticated owner on the server.</p><div className="mt-7 grid grid-cols-2 gap-3">{["Private storage", "Consent records", "Quota protection", "Secure downloads"].map((item) => <div className="panel-quiet px-4 py-3 text-sm" key={item}>{item}</div>)}</div></div></aside></main>;
}
